spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/avalon1?serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9999